### ISSUE TITLE
Delete never succeeds if you delete an object that would never have formed a cluster

### ISSUE THREAD

**Issue by jhgaylor** [digitalocean/do-operator#4]
This is the example from the readme. If you apply it, there are errors because num_nodes should be numNodes. If you then delete that object it never gets cleared out. If you manually delete the finalizers from the object using `kubectl edit database example` then the object clears out immediately.

I think the operator can reject the illegal object before it ever gets into the cluster so maybe this needn't be fixed directly.

```
apiVersion: doop.do.co/v1alpha1
kind: Database
metadata:
  name: example
spec:
  name: example
  engine: redis
  version: "5"
  size: db-s-2vcpu-4gb
  region: sfo2
  num_nodes: 2
  tags:
  - test
  - doop
```
